name: endernote
description: "Your versatile note-taking companion. Craft, create, and unleash your ideas with ease!"

version: 3.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  record: ^5.1.0
  sherpa_onnx: 1.11.3
  get: ^4.7.2 # 添加GetX依赖
  lottie: ^3.0.0
  flutter_svg: ^2.0.10+1
  flutter_markdown: ^0.7.3
  ficonsax: ^0.0.3
  equatable: ^2.0.5
  flutter_bloc: ^9.0.0
  path_provider: ^2.1.4
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2
  bloc: ^9.0.0
  path: ^1.9.0
  flutter_speed_dial: ^7.0.0
  file_picker: ^9.2.1
  logger: ^2.5.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/
    - lib/assets/icons/

  fonts:
    - family: FiraCode
      fonts:
        - asset: lib/assets/FiraCode.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: lib/assets/PlayfairDisplay.ttf
    - family: Roboto
      fonts:
        - asset: lib/assets/Roboto.ttf
    - family: Barriecito
      fonts:
        - asset: lib/assets/Barriecito.ttf
