name: xnote
description: "unleash your ideas with ease!"

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  record: ^5.1.0
  sherpa_onnx: 1.11.3
  get: ^4.7.2 # 添加GetX依赖
  flutter_svg: ^2.0.10+1
  ficonsax: ^0.0.3
  flutter_bloc: ^9.0.0
  path_provider: ^2.1.4
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2
  path: ^1.9.0
  flutter_speed_dial: ^7.0.0
  file_picker: ^9.2.1
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  markdown: ^7.3.0
  markdown_widget: ^2.3.2+8
  markdown_toolbar: ^0.5.0
  scroll_to_index: ^3.0.1
  visibility_detector: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/
    - lib/assets/icons/

  fonts:
    - family: FiraCode
      fonts:
        - asset: lib/assets/FiraCode.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: lib/assets/PlayfairDisplay.ttf
    - family: Roboto
      fonts:
        - asset: lib/assets/Roboto.ttf
    - family: Barriecito
      fonts:
        - asset: lib/assets/Barriecito.ttf
