name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  setup_flutter:
    name: 🚀 Set up Flutter
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            $HOME/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - run: flutter pub get
      - name: Create api_key.dart
        run: echo "const firebaseWebApi = \"${{ secrets.API_KEY }}\";" > lib/api_key.dart

  build_android:
    name: 🤖 Build Android App
    runs-on: ubuntu-latest
    needs: setup_flutter
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            $HOME/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - run: flutter build apk --release
      - name: Upload APK to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          tag: v1.0-${{ github.run_number }}
          overwrite: true
          body: "It's beta"

  build_windows:
    name: 🪟 Build Windows App
    runs-on: windows-latest
    needs: setup_flutter
    steps:
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            $HOME/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - run: flutter build windows --release
      - name: Upload Windows App to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build\windows\x64\runner\Release\endernote_flutter.exe
          tag: v1.0-${{ github.run_number }}
          overwrite: true
          body: "It's beta"

  build_linux:
    name: 🐧 Build Linux App
    runs-on: ubuntu-latest
    needs: setup_flutter
    steps:
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            $HOME/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux --release
      - run: cd build/linux/x64/release/bundle/ && zip -r linux.zip *
      - name: Upload Linux App to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/linux/x64/release/bundle/linux.zip
          tag: v1.0-${{ github.run_number }}
          overwrite: true
          body: "It's beta"
